Deposit
CryptoSFor/wallet pull request #1
Opened 2021-11-04 18:57 UTC by CryptoSFor

2021-11-08 07:59 UTC, xartishuk requested changes
Where are tests?

2021-11-08 07:59 UTC, xartishuk commented on README.md
> +Wallet is a type that allows the following operations: to deposit and withdraw money and get
newline in the middle of a sentence?

2021-11-08 07:59 UTC, xartishuk commented on wallet.go
> +	if math.Signbit(float64(b)) {
doesn't this work?
```
if float64(b) < 0 {
```

2021-11-08 17:24 UTC, CryptoSFor commented on README.md
> +Wallet is a type that allows the following operations: to deposit and withdraw money and get
Done

2021-11-08 17:24 UTC, CryptoSFor commented on wallet.go
> +	if math.Signbit(float64(b)) {
Done

2021-11-10 19:12 UTC, xartishuk approved these changes

2021-11-11 18:43 UTC, closed without merging